# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - task -l
  bootstrap:
    desc: "Bootstrap a dev environment"
    cmds:
      - echo "Installing virtualenv"
      - python3 -m venv .venv
      - source .venv/bin/activate
      - echo "Installing/Upgrading dependencies"
      - pip install --upgrade pip
      - pip install -e ".[test]"
