name: "Tag and build"
on:
  push:
    branches: ["main"]
    tags: ["*"]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
    - uses: pre-commit/action@v2.0.3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
  tagging:
    name: "Tagging"
    needs: pre-commit
    runs-on: ubuntu-latest
    outputs:
      next_tag: ${{ steps.tag_version.outputs.new_version }}
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          echo Calculated Next Tag is ${{ steps.tag_version.outputs.new_tag }}
  build:
    name: "Build docker image"
    runs-on: ubuntu-latest
    needs:
      - pre-commit
      - tagging
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Artifactory
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - run: echo jackbit/pyrriga:${{needs.tagging.outputs.next_tag}}

      - run: |
          docker build -t jackbit/pyrriga:${{needs.tagging.outputs.next_tag}} .

      - run: |
          docker push jackbit/pyrriga:${{needs.tagging.outputs.next_tag}}
